HZ.MVC.FaKa/Areas/Admin/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HZ.MVC.FaKa.Areas.Admin.Models
{
    public class OrderViewModel
    {
        public int Id
        {
            get;
            set;
        }
        public string NO
        {
            get;
            set;
        }
        public int Product_Id
        {
            get;
            set;
        }
        public string Type
        {
            get;
            set;
        }
        public string Status
        {
            get;
            set;
        }
        public double Price
        {
            get;
            set;
        }
        public int Count
        {
            get;
            set;
        }
        public string LocalStatus
        {
            get;
            set;
        }
        public string Remark
        {
            get;
            set;
        }
        public DateTime UpdateTime
        {
            get;
            set;
        }
    }
}

HZ.MVC.FaKa/Areas/Admin/Controllers/OrderController.cs
using HZ.MVC.FaKa.Areas.Admin.Models;
using HZ.MVC.FaKa.Areas.Admin.Models.Enum;
using HZ.MVC.FaKa.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HZ.MVC.FaKa.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {
        //
        // GET: /Admin/Order/

        public ActionResult Index()
        {
            if (Session["admin_User"] == null)
            {
                return RedirectToRoute(new { controller = "Account", action = "Login", area = "" });
            }
            ViewBag.title = "订单管理";
            return View();
        }

        public JsonResult GetOrders(int limit, int offset, string departmentname)
        {
            List<OrderViewModel> lstRes = null;
            if (!string.IsNullOrEmpty(departmentname))
                lstRes = BOrder.SearchByContact(departmentname);
            else
                lstRes = BOrder.SearchAll();

            var total = lstRes.Count;
            var rows = lstRes.Skip(offset).Take(limit).ToList();
            return Json(new { total = total, rows = rows }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete()
        {
            string name = Request.Form["pId"];

            List<DeleteId> models = LitJson.JsonMapper.ToObject<List<DeleteId>>(name);
            if (models == null)
            {
                return Content(ReturnMsg.fail.ToString());
            }

            bool isSucc = BOrder.Delete(models.Select(_ => _.Id).ToList());
            if (isSucc)
            {
                return Content(ReturnMsg.success.ToString());
            }
            else
            {
                return Content(ReturnMsg.fail.ToString());
            }
        }

        [Serializable]
        public class DeleteId
        {
            public int Id { get; set; }
        }
    }
}

HZ.MVC.FaKa/Controllers/HomeController.cs
using HZ.MVC.FaKa.Areas.Admin.Models;
using HZ.MVC.FaKa.BLL;
using HZ.MVC.FaKa.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HZ.MVC.FaKa.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (Request.Cookies != null && Request.Cookies.Count > 0)
            {
                HttpCookie cookie = Request.Cookies.Get("cmail");
                if (cookie != null)
                    ViewBag.ckie = cookie.Value;
            }
            var allPro = GetAllProducts();
            ViewBag.pros = allPro;

            ViewBag.Message = "一、支付宝付款后不要动，20秒左右自动跳转到卡密页面" + "\r\n" +
                              "二、微信付款后等待10秒左右，点击已完成付款 查询卡密";
            ViewBag.ZhuYi = "温馨提示：" + "\n" +
                            "1.可以不用注册，可直接付款购买，自动发货！无需等待即买即看" + "\n" +
                            "2.万一你付款成功网页被你关了，拿订单号或者联系方式到查询订单页面查询" + "\n" +
                            "3.为了保护您账号安全，会定期删档，买号后请收藏，不可分享不然封停后果自负" + "\n" +
                            "4.如有问题联系客服QQ：81651067 没有订单号不售后，没有库存联系客服上货";
            return View();
        }

        private List<ProductViewModel> GetAllProducts()
        {
            List<ProductViewModel> products = BProduct.SearchAll();
            return products;
        }

        public ActionResult About()
        {
            ViewBag.Message = "<p>一、支付宝付款后不要动，20秒左右自动跳转到卡密页面</p>" +
                              "<p>二、微信付款后等待10秒左右，点击已完成付款 查询卡密</p>";
                              
            ViewBag.ZhuYi = "<p>温馨提示：</p>" +
                            "<p>1.可以不用注册，可直接付款购买，自动发货！无需等待即买即看</p>" +
                            "<p>2.万一你付款成功网页被你关了，拿订单号或者联系方式到查询订单页面查询</p>" +
                            "<p>3.为了保护您账号安全，会定期删档，买号请收藏，不可分享不然封停后果自负</p>" +
                            "<p>4.如有问题联系客服QQ：81651067 没有订单号不售后，没有库存联系客服上货</p>" +
                            "<p>诚邀各路大牛共造双赢，一手货源，实力批发，诚信经营</p>" +
                            "<p>本店专业批发各大影视Vip、各种业务卡密、QQ号等</p>" +
                            "<p>有实力可以跑量的联系我，量大价格肯定美丽！</p>" +
                            "<p>购买5件起，可享受批发价！提交订单查看价格</p>";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public bool ExisitCookie(string email)
        {
            if (Request.Cookies != null && Request.Cookies.Count > 0)
            {
                HttpCookie cookie = Request.Cookies.Get("cmail");
                if (cookie != null && cookie.Value.Trim().ToLower() == email.Trim().ToLower())
                    return true;
                else
                    return false;
            }
            return false;
        }


        public ActionResult Order()
        {



            return View();
        }

        /// <summary>
        ///  确定订单
        /// </summary>
        /// <returns></returns>
        public ActionResult Confirm()
        {
            string email = Request.QueryString["mail"];
            string id = Request.QueryString["id"];
            string num = Request.QueryString["num"];
            string random = Request.QueryString["t"];

            ProductViewModel p = BProduct.SearchById(id);
            if (p == null)
            {
                return View();
            }
            double totalMoney = Convert.ToInt32(num) * p.Price;

            ViewBag.Email = email;
            ViewBag.Id = id;
            ViewBag.Num = num;
            ViewBag.Total = totalMoney;
            ViewBag.Name = p.Name;
            ViewBag.SinglePrice = p.Price;

            if (!ExisitCookie(email))
            {
                HttpCookie cookie = new HttpCookie("cmail", email);
                cookie.Path = "/";
                cookie.Domain = "1777ka.com";
                cookie.Expires = DateTime.Now.AddYears(10);
                Response.Cookies.Add(cookie);
            }
            return View();
        }
    }
}

HZ.MVC.FaKa/Controllers/WxPayController.cs
using HZ.MVC.FaKa.Areas.Admin.Models;
using HZ.MVC.FaKa.BLL;
using HZ.MVC.FaKa.Common;
using Microsoft.Web.WebPages.OAuth;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using WxPayAPI;

namespace HZ.MVC.FaKa.Controllers
{
    public class WxPayController : Controller
    {
        //
        // GET: /WxPay/

        public ActionResult Index()
        {

            return View();
        }


        /// <summary>
        /// 订单生成
        /// </summary>
        /// <returns></returns>
        public ActionResult Order()
        {
            string proId = Request.Form["proId"];
            string name = Request.Form["proName"];
            string price = Request.Form["price"];
            string num = Request.Form["num"];
            string email = Request.Form["email"];

            ProductViewModel model = BProduct.SearchById(proId);
            if (model == null)
            {
                return Content("订单生成异常");
            }

            double _price = Convert.ToDouble(price);
            int _num = Convert.ToInt32(num);

            if (model.Price != _price)
            {
                return Content("订单生成异常(金额不符)");
            }
            if (model.Name != name)
            {
                return Content("订单生成异常(名称不符)");
            }

            double totalPrice = _price * _num;
            string orderNo = DTHelper.GetCurrentTimeOrderNo();
            //订单生成
            OrderViewModel orderModel = new OrderViewModel();
            orderModel.Count = _num;
            orderModel.NO = orderNo;
            orderModel.Price = _price;
            orderModel.Product_Id = Convert.ToInt32(proId);
            orderModel.Remark = email;
            orderModel.Type = Request.Form["paytype"];
            orderModel.LocalStatus = "待支付";
            orderModel.UpdateTime = DateTime.Now;
            BOrder.Insert(orderModel);

            string url = "";

            if (orderModel.Type == "1")
            {
                NativePay nativePay = new NativePay();

                //转化为以分为单位的金额
                int money = Convert.ToInt32(totalPrice * 100);
                //生成扫码支付模式二url
                url = "https://www.baifubao.com/o2o/0/qrcode?size=4&text=" + nativePay.GetPayUrl(proId, money, name, orderNo);
            }
            else if (orderModel.Type == "2")
            {
                url = "/Zhifu/precreate.aspx?tid=" + orderNo;
            }
            else { }

            ViewBag.QR_url = url;
            ViewBag.Name = name;
            ViewBag.Num = _num;
            ViewBag.Total = totalPrice;
            ViewBag.tNo = orderNo;
            ViewBag.payType = Request.Form["paytype"];
            return View();
        }

        public ActionResult KaMiList()
        {
            //查询卡密，并显示
            string tNo = Request.QueryString["tNo"];
            OrderViewModel order = BOrder.SearchByTradeNo(tNo);
            if (order == null)
                return View();

            Dictionary<int, string> kamis = BKaMi.SearchKamiByTrade(order);

            #region 更新卡密状态为已使用
            List<KaMiViewModel> models = new List<KaMiViewModel>();
            foreach (var item in kamis)
            {
                KaMiViewModel ka = new KaMiViewModel();
                ka.Id = item.Key;
                ka.Remark = order.Remark;
                ka.Trade_No = tNo;
                models.Add(ka);
            }
            BKaMi.UpdateBySql(models);
            #endregion

            string dir = Server.MapPath("~/Files") ;
            string path = dir + "/" + tNo + ".csv";
            using (StreamWriter writer = new StreamWriter(path, true, Encoding.UTF8))
            {
                string title = "订单号,卡密内容,联系方式\r\n";
                writer.Write(title);

                string content = "";

                foreach (var item in kamis)
                {
                    content += tNo + "," + item.Value + "," + order.Remark + "\r\n";
                }
                writer.Write(content);
            }
            ViewBag.tNo = tNo;
            return View(kamis);
        }

        public ActionResult DownLoadFile(string tNo)
        {
            string dir = Server.MapPath("~/Files");
            string downFile = dir + "/" + tNo + ".csv";
            return File(downFile, "text/plain", tNo + ".csv");
        }

        public ActionResult SearchByContact()
        {
            string contact = Request.Form["contact"];
            Regex regex = new Regex(@"^\b[A-Z]+\d+\b$");
            Dictionary<int, string> kamis = new Dictionary<int, string>();
            string tNo = "";
            if (!regex.IsMatch(contact))
            {
                kamis = BKaMi.SearchKamiByContact(contact, ref tNo);
                if (kamis.Count == 0)
                    return Content("未查到对应订单信息");
            }
            else
            {
                kamis = BKaMi.SearchKamiByContact("",ref contact);
                tNo = contact;
                if (kamis.Count == 0)
                    return Content("未查到对应订单信息");
            }
            ViewBag.tNo = tNo;
            return View("KaMiList", kamis);
        }

        public JsonResult CheckPayResult()
        {
            string tradeNo = Request["trade_no"];
            string payType = Request["payway"];

            OrderViewModel model = BOrder.SearchByTradeNo(tradeNo);
            if (model == null)
            {
                var result = new { code = "-2", msg = "not exists" };
                return Json(LitJson.JsonMapper.ToJson(result));
            }

            if (model.LocalStatus != "已付款")
            {
                var result = new { code = "-1", msg = "wait for pay" };
                return Json(LitJson.JsonMapper.ToJson(result));
            }
            else
            {
                var result = new { code = "1", msg = "success" };
                return Json(LitJson.JsonMapper.ToJson(result));
            }
        }

        /// <summary>
        /// 支付回调
        /// </summary>
        /// <returns></returns>
        public ActionResult GetPayResult()
        {
            string resultFromWx = getPostStr();
            if (string.IsNullOrEmpty(resultFromWx))
                return View();
            //string path = Path.Combine(Server.MapPath("~/data"), "data" + DateTime.Now.ToString("yyyyMMddHHmmss") + ".txt");
            //FileInfo f = new FileInfo(path);
            //if (!Directory.Exists(f.DirectoryName))
            //    Directory.CreateDirectory(f.DirectoryName);
            //using (StreamWriter writer = new StreamWriter(path))
            //{
            //    writer.Write(resultFromWx);
            //}

            var res = XDocument.Parse(resultFromWx);

            //通信成功
            try
            {
                if (res.Element("xml").Element("return_code").Value == "SUCCESS")
                {
                    if (res.Element("xml").Element("result_code").Value == "SUCCESS")
                    {
                        //交易成功
                        string transaction_id = res.Element("xml").Element("transaction_id").Value;//微信订单号
                        string trade_no = res.Element("xml").Element("out_trade_no").Value;//商户订单号

                        //查询订单是否存在
                        OrderViewModel model = BOrder.SearchByTradeNo(trade_no);
                        if (model != null)
                        {
                            //存在
                            BOrder.Update("update Orders set LocalStatus='已付款' where Id=" + model.Id);
                        }
                        return Content(CallWxSuccess());
                    }
                    else
                    {
                        return Content("支付出现问题，请返回重试");
                    }
                }
            }
            catch (Exception e)
            {

            }
            return Content("failed");
        }

        public string CallWxSuccess()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("<xml>");
            builder.Append("<return_code><![CDATA[SUCCESS]]></return_code>");
            builder.Append("<return_msg><![CDATA[OK]]></return_msg>");
            builder.Append("</xml>");
            return builder.ToString();
        }

        public string CallWxFail()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("<xml>");
            builder.Append("<return_code><![CDATA[FAIL]]></return_code>");
            builder.Append("<return_msg><![CDATA[OK]]></return_msg>");
            builder.Append("</xml>");
            return builder.ToString();
        }

        /// <summary>
        /// 获取 Post 提交的参数
        /// </summary>
        /// <returns></returns>
        public string getPostStr()
        {
            Int32 intLen = Convert.ToInt32(Request.InputStream.Length);
            byte[] b = new byte[intLen];
            Request.InputStream.Read(b, 0, intLen);
            return System.Text.Encoding.UTF8.GetString(b);
        }

    }
}

HZ.MVC.FaKa/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h2>@Html.Raw(ViewBag.Message)</h2>
</hgroup>

<article>

    @Html.Raw(ViewBag.ZhuYi)

</article>

HZ.MVC.FaKa/Views/Home/Confirm.cshtml
@{
    ViewBag.Title = "订单确认";
}
<link rel="stylesheet" href="/Content/bankList.css" charset="utf-8">
<link type="text/css" rel="stylesheet" href="/Content/widget.css" source="widget">
<link type="text/css" rel="stylesheet" href="/Content/unit.css">
<link charset="utf-8" rel="stylesheet" href="/Content/tips.css">
<style type="text/css">
    .wq-list {
        padding: 10px 0px;
    }

    .method-list-p {
        list-style: none;
        padding-left: 0;
        margin-bottom: 10px;
        color: #a9afb5 !important;
        text-align: left !important;
    }

    .method-list {
        list-style: none;
        margin-bottom: 0;
        padding-left: 0;
    }

        .method-list .method-alipay {
            display: inline;
            float: left;
            margin: 0 20px;
        }

        .method-list .method-box {
            border: 1px solid #CCC;
            padding: 11px 12px;
            cursor: pointer;
        }

        .method-list .method-radio {
            display: none;
        }

        .method-list .method-alipay .method-box.method-current {
            background-color: #EFF9FF;
            border-color: #00AAEE;
        }

        .method-list .method-qqpay {
            display: inline;
            float: left;
            margin: 0 0px 0px 0;
        }

    label {
        font-weight: 300;
    }

    label {
        display: inline-block;
        max-width: 100%;
        margin-bottom: 5px;
        font-weight: bold;
    }

    .method-list .method-qqpay .method-box.method-current {
        background-color: #EFF9FF;
        border-color: #00AAEE;
    }

    .method-list .method-box.method-current {
        border-width: 2px;
        padding: 10px 11px;
        border-color: #f37800;
        background-color: #FFF6E7;
    }
</style>
<div id="container">
    @using (Html.BeginForm("Order", "WxPay", FormMethod.Post))
    {
        <input type="hidden" name="proId" value="@ViewBag.Id" />
        <input type="hidden" name="proName" value="@ViewBag.Name" />
        <input type="hidden" name="price" value="@ViewBag.SinglePrice" />
        <input type="hidden" name="num" value="@ViewBag.Num" />
        <input type="hidden" name="email" value="@ViewBag.Email" />
        <div id="content" class="w">

            <div class="checkout-tit">
                <span class="tit-txt">填写并核对订单信息</span>
            </div>

            <div class="checkout-steps">

                <div class="step-tit">
                    <h3>订单信息</h3>
                </div>
                <div class="hr"></div>
                <div class="step-cont">
                    <div id="consignee-addr" class="consignee-content">
                        <div class="consignee-scrollbar">
                            <div class="ui-scrollbar-main">
                                <div class="consignee-scroll">
                                    <div class="consignee-cont" id="consignee1">
                                        <p>订单名称:<font color="red" style="padding:0 10px;">@ViewBag.Name</font></p>
                                        <p>订单数量:<font color="red" style="padding:0 10px;">@ViewBag.Num</font></p>
                                        <p>订单价格:<font color="red" style="padding:0 10px;">@ViewBag.SinglePrice</font></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="hr"></div>

                <div id="shipAndSkuInfo">
                    <div id="payShipAndSkuInfo">
                        <div class="step-tit">
                            <h3>支付方式</h3>
                        </div>
                        <div class="hr"></div>
                        <div class="step-cont">
                            <div class="payment-list" id="">
                                <div class="list-cont">

                                    <ul class="method-list clearfix">
                                        <li class="method-alipay">
                                            <input type="radio" name="paytype" value="1" class="method-radio" id="qqpay" checked="checked">
                                            <label class="method-box method-current" for="qqpay">
                                                <img src="/Images/wx.png" alt="使用微信支付" width="94">
                                            </label>
                                        </li>
                                        <li class="method-qqpay">
                                            <input type="radio" name="paytype" value="2" class="method-radio" id="alipay">
                                            <label class="method-box" for="alipay">
                                                <img src="/Images/alipay.png" alt="使用支付宝支付" width="94">
                                            </label>
                                        </li>
                                    </ul>



                                </div>
                            </div>
                        </div>

                    </div>
                </div>



            </div>

            <div class="order-summary">

                <div class="statistic fr">
                    <div class="list">
                        <span><em class="ftx-01">1</em> 件商品，总商品金额：</span>
                        <em class="price" id="warePriceId">￥@ViewBag.Total</em>
                    </div>

                </div>
                <div class="clr"></div>
            </div>

            <div class="trade-foot">
                <div class="trade-foot-detail-com">
                    <div class="fc-price-info">
                        <span class="price-tit">应付总额：</span>
                        <span class="price-num" id="sumPayPriceId">￥@ViewBag.Total</span>
                    </div>

                    <div class="fc-consignee-info">
                        <span id="sendMobile">收货人：@ViewBag.Email</span>
                    </div>
                </div>

                <div id="checkout-floatbar" class="group">
                    <div class="ui-ceilinglamp checkout-buttons">
                        <div class="sticky-placeholder hide" style="display: none;">
                        </div>
                        <div class="sticky-wrap">
                            <div class="inner">
                                <button type="submit" class="checkout-submit" id="order-submit">
                                    提交订单<b></b>
                                </button>

                                <span id="checkCodeDiv"></span>
                                <div class="checkout-submit-tip" id="changeAreaAndPrice" style="display: none;">
                                    由于价格可能发生变化，请核对后再提交订单
                                </div>
                            </div>
                            <span id="submit_message" style="display:none" class="submit-error"></span>
                            <div class="submit-check-info" id="submit_check_info_message" style="display:none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section scripts
{
    <script type="text/javascript">
        $(function () {
            for (var i = 0; i < $('.method-list > li').length; i++) {
                $('.method-list > li').eq(i).children('.method-box').removeClass('method-current');
            }
            var ischeck = $("input:radio:checked").val();
            if(ischeck == "2")
            {
                $('#alipay').parent().find('.method-box').addClass('method-current')
            }
            else
            {
                $('#qqpay').parent().find('.method-box').addClass('method-current')
            }
        });
        $('.amount-list > li').click(function () {
            for (var i = 0; i < $('.amount-list > li').length; i++) {
                $('.amount-list > li').eq(i).children('.amount-box').removeClass('amount-current');
            }
            $(this).children('.amount-box').addClass('amount-current');
            $("#amount").val($(this).children('.amount-radio').val());
        });
        $('.method-list > li').click(function () {
            for (var i = 0; i < $('.method-list > li').length; i++) {
                $('.method-list > li').eq(i).children('.method-box').removeClass('method-current');
            }
            $(this).children('.method-box').addClass('method-current');
            $("#method").val($(this).children('.method-radio').val());
        });
    </script>
}

HZ.MVC.FaKa/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "联系方式";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    
</hgroup>

<section class="contact">
    <header>
        <h3>电话</h3>
    </header>
    <p>
        <span class="label">手机:</span>
        <span>13603842142</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">QQ-Mail:</span>
        <span><a href="mailto:455531105@qq.com">455531105@qq.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>地址</h3>
    </header>
    <p>
        河南郑州
    </p>
</section>